### ISSUE TITLE
Why using ROC_AUC in code but PR_AUC in paper?

### ISSUE THREAD

**Issue by Weile0409** [GentleZhu/CG-MuAlign#1]
Dear author, I appreciate this job very much !!!
I would like to ask why using ROC_AUC in code but PR_AUC in paper?
Another question is how to calculate Rec@Prec=.95, as shown in your paper?
Thank you!

**Comment by GentleZhu** [comment]
Hi,
As you may know, the release code is a reference implementation for public visibility such that it's different from the paper experiments. There is no particular reason to use ROC_AUC but PR_AUC, you can use both for comprehensive study. In entity alignment in real world, you will have a blocking function that generates the candidate pairs. So what we did in the paper is using a random negative generator as blocking function (same for real blockers), you can tune the threshold to make your algorithm hit 95% precision and report the recall numbers

**Comment by Weile0409** [comment]
Oh i see ! Thank you for your reply ! I appreciate all of your interesting works for the GNN :))
Have a nice day !
